# Generated by Django 5.1.7 on 2025-03-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bouquet',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='name',
            new_name='sort',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='description',
        ),
        migrations.DeleteModel(
            name='Bouquet',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
