# Generated by Django 5.1.7 on 2025-06-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_remove_order_bouquet_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='price',
            field=models.IntegerField(),
        ),
    ]
